openapi: 3.0.1
info:
  title: WebApi Service
  description: WebApi Service
  termsOfService: http://www.example.com
  contact:
    name: Swagger Codegen Contributors
    url: https://github.com/swagger-api/swagger-codegen
    email: ''
  version: 1.0.0
paths:
  /v1/data:
    get:
      tags:
        - Data
      summary: Get data
      operationId: getData
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataDto'
  /v1/data/{userId}:
    get:
      tags:
        - Data
      summary: Get data for user
      operationId: getDataForUser
      parameters:
        - name: userId
          in: path
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataDto'
        '404':
          description: User Not Found
components:
  schemas:
    DataDto:
      type: object
      properties:
        Id:
          type: string
        Info:
          type: string
